#!/bin/sh

if [ ! -d /var/lib/mysql/mysql ]; then
    chown -R mysql:mysql /var/lib/mysql
    /usr/bin/mysql_install_db --defaults-file=/etc/mysql/my.cnf
fi

/usr/bin/mysqld_safe --user=root --init-file=/root/docker/scripts/fix_access.sql && \ 
/usr/bin/mysqld_safe --user=root